"""Generate paper/codex_numbers.tex from experiments/H_codex_six_runs/summary.json.

Workflow:
    1. After Codex runs finish, run experiments/H_codex_six_runs/aggregate.py
    2. Run this script to populate paper/codex_numbers.tex
    3. Compile paper/short_codex.tex with pdflatex/bibtex

Usage:
    pixi run python paper/build_short_codex.py
"""
import json
import os


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUMMARY_PATH = os.path.join(PROJECT_ROOT, "experiments", "H_codex_six_runs", "summary.json")
OUT_PATH     = os.path.join(PROJECT_ROOT, "paper", "codex_numbers.tex")
BASELINE_ROWP = 4246.7


ROMAN = ("I", "II", "III")


def fmt_num(x, prec=1):
    if x is None:
        return "TBD"
    return f"{x:.{prec}f}"


def fmt_struct(structs):
    if not structs:
        return "(no motif matched)"
    return ", ".join(s.replace("_", "-") for s in structs)


def fmt_modal(structs):
    """Pick a single dominant modality label for full-opt classification."""
    if not structs:
        return "(unclassified)"
    priorities = ["wraps_slsqp", "wraps_topfarm_sgd", "cma_es",
                  "genetic_algorithm", "custom_adam"]
    for p in priorities:
        if p in structs:
            return p.replace("_", "-")
    return structs[0].replace("_", "-")


def narrow_verdict(sched_runs):
    """Return a verdict string for the narrow interface."""
    feasible = [r for r in sched_runs if r.get("rowp_aep") and r.get("rowp_feasible")]
    if not feasible:
        return "no feasible run"
    rowp = [r["rowp_aep"] for r in feasible]
    discoveries = sum(1 for r in feasible
                      if any(s in r.get("structures", [])
                             for s in ("dual_gaussian_bumps",
                                       "cosine_restart",
                                       "cyclic_betas",
                                       "alpha_squeeze")))
    if discoveries >= 2 and max(rowp) > BASELINE_ROWP + 10:
        return "discovery"
    if max(rowp) > BASELINE_ROWP + 10:
        return "beats baseline (motif unclear)"
    return "baseline-equivalent"


def broad_verdict(full_runs):
    feasible = [r for r in full_runs if r.get("rowp_aep") and r.get("rowp_feasible")]
    if not feasible:
        return "no feasible run"
    n_slsqp = sum(1 for r in feasible if "wraps_slsqp" in r.get("structures", []))
    n_sgd   = sum(1 for r in feasible if "wraps_topfarm_sgd" in r.get("structures", []))
    n_cust  = sum(1 for r in feasible
                  if any(s in r.get("structures", []) for s in
                         ("genetic_algorithm", "cma_es")))
    if n_slsqp + n_sgd >= 2:
        if n_slsqp >= 2:
            return "reimpl (SLSQP)"
        if n_sgd >= 2:
            return "reimpl (SGD-wrapper)"
        return "reimpl (mixed)"
    if n_cust >= 2:
        return "novel (GA/CMA)"
    return "mixed"


def main():
    if not os.path.exists(SUMMARY_PATH):
        print(f"[build_short_codex] {SUMMARY_PATH} not found.")
        print("[build_short_codex] Run experiments/H_codex_six_runs/aggregate.py first.")
        return

    s = json.load(open(SUMMARY_PATH))
    sched_runs   = s["sched"]["runs"]
    full_runs    = s["fullopt"]["runs"]
    sched_summ   = s["sched"]["summary"]
    full_summ    = s["fullopt"]["summary"]

    lines = ["% Generated by paper/build_short_codex.py — do not edit by hand.", ""]

    def cmd(name, value):
        lines.append(f"\\renewcommand{{\\{name}}}{{{value}}}")

    # Seed-by-seed
    for i in range(3):
        rn = ROMAN[i]
        r_sched = sched_runs[i] if i < len(sched_runs) else {}
        r_full  = full_runs[i]  if i < len(full_runs)  else {}
        cmd(f"CodexSchedTrainS{rn}",  fmt_num(r_sched.get("train_aep")))
        cmd(f"CodexSchedRowpS{rn}",   fmt_num(r_sched.get("rowp_aep")))
        cmd(f"CodexSchedStructS{rn}", fmt_struct(r_sched.get("structures", [])))
        cmd(f"CodexFullTrainS{rn}",   fmt_num(r_full.get("train_aep")))
        cmd(f"CodexFullRowpS{rn}",    fmt_num(r_full.get("rowp_aep")))
        cmd(f"CodexFullModalS{rn}",   fmt_modal(r_full.get("structures", [])))

    # Aggregates
    cmd("CodexSchedTrainMean", fmt_num(sched_summ.get("train_mean")))
    cmd("CodexSchedTrainStd",  fmt_num(sched_summ.get("train_std")))
    cmd("CodexSchedRowpMean",  fmt_num(sched_summ.get("rowp_mean")))
    cmd("CodexSchedRowpStd",   fmt_num(sched_summ.get("rowp_std")))

    # Abstract slot fillers
    best_sched_rowp = sched_summ.get("rowp_max")
    if best_sched_rowp:
        cmd("BestSchedROWP", f"{best_sched_rowp:.1f}")
        cmd("DeltaSchedROWP", f"{best_sched_rowp - BASELINE_ROWP:.1f}\\,GWh")

    nv = narrow_verdict(sched_runs)
    bv = broad_verdict(full_runs)
    cmd("CodexNarrowVerdict", nv)
    cmd("CodexBroadVerdict",  bv)

    # Match abstract phrasing roughly
    if "discovery" in nv:
        cmd("SchedStructuralCharacterization", "matching the structural pattern observed in")
    elif "beats baseline" in nv:
        cmd("SchedStructuralCharacterization", "novel relative to")
    else:
        cmd("SchedStructuralCharacterization", "qualitatively different from")

    if "reimpl (SLSQP)" in bv:
        cmd("FullModalChoice", "SLSQP, matching Gemini's full-optimizer pattern")
    elif "reimpl (SGD" in bv:
        cmd("FullModalChoice", "an SGD wrapper, matching Claude's full-optimizer pattern")
    elif "novel" in bv:
        cmd("FullModalChoice", "a non-standard solver (GA or CMA-ES variant)")
    else:
        cmd("FullModalChoice", "a mixture of approaches across seeds")

    # Narrow-vs-broad outcome
    holds = ("discovery" in nv) and ("reimpl" in bv)
    if holds:
        cmd("NarrowBroadOutcome", "holds")
        cmd("StrengthOfEvidence", "strong")
    elif ("discovery" in nv) and ("novel" in bv):
        cmd("NarrowBroadOutcome", "is partially preserved (broad is also novel)")
        cmd("StrengthOfEvidence", "moderate")
    elif ("baseline-equivalent" in nv):
        cmd("NarrowBroadOutcome", "fails on the narrow side")
        cmd("StrengthOfEvidence", "weakening")
    else:
        cmd("NarrowBroadOutcome", "is mixed")
        cmd("StrengthOfEvidence", "moderate")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[build_short_codex] Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
